version: '3'

services:
  app:
    build: '.'
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - '3000:3000'
    entrypoint:
      - npm
      - run
      - dev
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb:/data/mongodb